name: Hello Flow

on:
  schedule:
    - cron: '0 */12 * * *'

jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Diga oi
        run: echo "Hello World!"
      - name: Diga valeu
        run: echo "Valeu - bye!"
